[build]
  base = "gentsconcerts-app"
  publish = "dist"
  command = "npm install --legacy-peer-deps && npx expo export --platform web --clear"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
